---
- name: Install dotprofiles with Ansible.
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Gather facts.
      ansible.builtin.setup:
        gather_subset:
          - min

    - name: Install dotbashprofiles if shell is bash.
      ansible.builtin.template:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"
        mode: u=rw,g=r,o=r
        backup: true
      when: ansible_facts['user_shell'] is ansible.builtin.search('bash')
      loop:
        - src: bash_profile
          dest: "{{ ansible_facts['user_dir'] }}/.bash_profile"
        - src: bashrc
          dest: "{{ ansible_facts['user_dir'] }}/.bashrc"

    - name: Install dotzshprofiles if shell is zsh.
      ansible.builtin.template:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"
        mode: u=rw,g=r,o=r
        backup: true
      when: ansible_facts['user_shell'] is ansible.builtin.search('zsh')
      loop:
        - src: zprofile
          dest: "{{ ansible_facts['user_dir'] }}/.zprofile"
        - src: zshrc
          dest: "{{ ansible_facts['user_dir'] }}/.zshrc"

    - name: Install dotaliases.
      ansible.builtin.template:
        src: aliases
        dest: "{{ ansible_facts['user_dir'] }}/.aliases"
        mode: u=rw,g=r,o=r
        backup: true

    - name: Ensure directory for neovim is present.
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.config/nvim"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Install init.lua for neovim.
      ansible.builtin.template:
        src: init.lua
        dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/init.lua"
        mode: u=rw,g=r,o=r
        backup: true

    - name: Ensure directory for tmux is present.
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.{{ item }}"
        state: directory
        mode: u=rwx,g=rx,o=rx
      loop:
        - config/tmux
        - tmux/plugins/tpm

    - name: Install tmux.conf for tmux.
      ansible.builtin.template:
        src: tmux.conf
        dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/tmux.conf"
        mode: u=rw,g=r,o=r
        backup: true

    - name: Install tmux plugin manager.
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_facts['user_dir'] }}/./tmux/plugins/tpm"
