#!/bin/zsh

# =================== General ==================

autoload -U compinit; compinit             # Enable the zsh completion system.
unsetopt BEEP                              # Disable terminal bell.
setopt AUTO_CD                             # Go to folder path without using cd.
setopt MENU_COMPLETE                       # Automatically highlight first element of completion menu.
setopt AUTO_LIST                           # Automatically list choices on ambiguous completion.
setopt PROMPT_SUBST                        # Enable parameter expansion, command substitution and arithmetic expansion in the prompt.

# =================== Export =====================

if test -d /opt/homebrew/bin; then         # Add homebrew's bin and sbin to path.
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
fi

if (which pyenv &>/dev/null); then         # Add pyenv's bin to path.
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init --path)"
fi

if (which vim &>/dev/null); then           # Set vim as editor.
  export VISUAL=vim
fi

export LANG=en_US.UTF-8                    # Use english (us) and UTF-8 encoding for console output.
export CLICOLOR=1                          # Enable colors.
export LSCOLORS=GxFxCxDxBxegedabagaced     # Customising the colors.

# =================== Alias ====================

alias c='clear'
alias ll='ls -l'
alias l='ls -lart'

if (which vim &>/dev/null); then
  alias vi='vim'
fi

if (which python3 &>/dev/null); then
  alias python='python3'
fi

if (which git &>/dev/null); then
  alias s='git status'
fi

# =================== Git branch ===============

if (which git &>/dev/null); then
  parse_git_branch() { git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1) /'; }
else
  parse_git_branch() { :; }
fi

# =================== Prompt ===================

nocolor='%f'                               # All attributes off.
green='%F{green}'                          # Green frontground color.
yellow='%F{yellow}'                        # Yellow frontground color.
cyan='%F{cyan}'                            # Cyan frontground color.

open_brk='${nocolor}['                     # The '[' bracket.
closed_brk='${nocolor}]'                   # The ']' bracket.
username='${green}%n'                      # The username of the current user.
at='${nocolor}@'                           # The '@' sign.
hostname='${nocolor}%m'                    # The hostname up to the first `.'
working_dir='${cyan}%2~'                   # The current working directory, with $HOME abbreviated with a tilde (2 trailing components of current dir).
git_branch='${yellow}$(parse_git_branch)'  # The current git branch.
prompt_indicator='${nocolor}%(!.#.$)'      # A '#' if the shell is running with privileges, a '$' if not.

PS1="${open_brk}${username}${at}${hostname} ${working_dir} ${git_branch}${closed_brk}${prompt_indicator} "
