---
# vars file for dot

__dot_bash_profiles:
  - .bash_profile
  - .bashrc
  - .bash_aliases

__dot_nvim_directories:
  - "{{ ansible_facts['user_dir'] }}/.local/share/nvim/site/pack/plugins/start"
  - "{{ ansible_facts['user_dir'] }}/.config/nvim/lua"
  - "{{ ansible_facts['user_dir'] }}/.config/nvim/lsp"

__dot_nvim_files:
  - src: "{{ playbook_dir }}/.config/nvim/init.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/init.lua"
  - src: "{{ playbook_dir }}/.config/nvim/lua/autocmds.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/lua/autocmds.lua"
  - src: "{{ playbook_dir }}/.config/nvim/lua/keymaps.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/lua/keymaps.lua"
  - src: "{{ playbook_dir }}/.config/nvim/lua/options.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/lua/options.lua"
  - src: "{{ playbook_dir }}/.config/nvim/lua/plugins.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/lua/plugins.lua"
  - src: "{{ playbook_dir }}/.config/nvim/lsp/ansible.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/lsp/ansible.lua"
  - src: "{{ playbook_dir }}/.config/nvim/lsp/python.lua"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/lsp/python.lua"
