---
# tasks file for dot

- name: tmux | Ensure directory for tmux is present.
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/tmux"
    mode: "{{ dot_mode_dir }}"
    state: directory

- name: tmux | Install configuration for tmux.
  ansible.builtin.template:
    src: "{{ playbook_dir }}/.config/tmux/tmux.conf"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/tmux.conf"
    mode: "{{ dot_mode_file }}"
    backup: true
