---
# tasks file for dot

- name: vim | Ensure directories for vim is present.
  ansible.builtin.file:
    path: "{{ dot_item }}"
    state: directory
    mode: "{{ dot_mode_dir }}"
  loop: "{{ __dot_vim_directories }}"
  loop_control:
    loop_var: dot_item

- name: vim | Install configuration for vim.
  ansible.builtin.template:
    src: "{{ playbook_dir }}/.vimrc"
    dest: "{{ ansible_facts['user_dir'] }}/.vimrc"
    mode: "{{ dot_mode_file }}"
    backup: true

- name: vim | Download plug.vim.
  ansible.builtin.get_url:
    url: "{{ dot_vim_plug_url }}"
    dest: "{{ ansible_facts['user_dir'] }}/.vim/autoload/plug.vim"
    mode: "{{ dot_mode_file }}"
